import { Edge } from "react-flow-renderer";

const InitialEdgesLaravel: Edge<any>[] = [
  {
    id: "l-edge-fundamental-controller",
    source: "l-node-fundamental",
    target: "l-node-controllers",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-create",
    source: "l-node-fundamental",
    target: "l-node-create-react-app",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-routing",
    source: "l-node-fundamental",
    target: "l-node-routing",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-database-relationships",
    source: "l-node-database",
    target: "l-node-relationships",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-forms",
    source: "l-node-fundamental",
    target: "l-node-forms",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-crud",
    source: "l-node-fundamental",
    target: "l-node-crud",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-database",
    source: "l-node-fundamental",
    target: "l-node-database",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-mvc",
    source: "l-node-fundamental",
    target: "l-node-mvc",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-relationships-relations",
    source: "l-node-relationships",
    target: "l-node-relations",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },





  // GREENS
  {
    id: "l-edge-fundamental-advanced",
    source: "l-node-fundamental",
    target: "l-node-advanced",
    animated: true,
    style: { stroke: "green" },
  },
  {
    id: "l-edge-advanced-mid",
    source: "l-node-advanced",
    target: "l-node-mid",
    animated: true,
    style: { stroke: "green" },
  },
  {
    id: "l-edge-head-fundamental",
    source: "l-node-head",
    target: "l-node-fundamental",
    animated: true,
    style: { stroke: "green" },
  },

  // END GREEN
  {
    id: "l-edge-database-migrations",
    source: "l-node-database",
    target: "l-node-migrations",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-database-seeders",
    source: "l-node-database",
    target: "l-node-seeders",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-routing-route-parameters",
    source: "l-node-routing",
    target: "l-node-route-parameters",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-routing-route-groups",
    source: "l-node-routing",
    target: "l-node-route-groups",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-blade",
    source: "l-node-fundamental",
    target: "l-node-blade",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-fundamental-auth",
    source: "l-node-fundamental",
    target: "l-node-auth",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-api",
    source: "l-node-advanced",
    target: "l-node-api",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-middleware",
    source: "l-node-advanced",
    target: "l-node-middleware",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-route-bindings",
    source: "l-node-advanced",
    target: "l-node-route-bindings",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-database-adv",
    source: "l-node-advanced",
    target: "l-node-database-adv",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-file",
    source: "l-node-advanced",
    target: "l-node-file",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-debug",
    source: "l-node-advanced",
    target: "l-node-debug",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-database-adv-query",
    source: "l-node-database-adv",
    target: "l-node-query",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-database-adv-accessors",
    source: "l-node-database-adv",
    target: "l-node-accessors",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-database-adv-collections",
    source: "l-node-database-adv",
    target: "l-node-collections",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-mail",
    source: "l-node-advanced",
    target: "l-node-mail",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-api-error",
    source: "l-node-api",
    target: "l-node-error",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-api-apps",
    source: "l-node-api",
    target: "l-node-apps",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-api-api-routes",
    source: "l-node-api",
    target: "l-node-api-routes",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-api-resources",
    source: "l-node-api",
    target: "l-node-resources",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-advanced-try",
    source: "l-node-advanced",
    target: "l-node-try",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-mid-eloquent-features",
    source: "l-node-mid",
    target: "l-node-eloquent-features",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-mid-raw",
    source: "l-node-mid",
    target: "l-node-raw",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-mid-jobs",
    source: "l-node-mid",
    target: "l-node-jobs",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-mid-observers",
    source: "l-node-mid",
    target: "l-node-observers",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-mid-caching",
    source: "l-node-mid",
    target: "l-node-caching",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-mid-only-api",
    source: "l-node-mid",
    target: "l-node-only-api",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "l-edge-mid-file-api",
    source: "l-node-mid",
    target: "l-node-file-api",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
];

export default InitialEdgesLaravel;