import { Edge } from "react-flow-renderer";

const InitialEdgesLaravel: Edge<any>[] = [
  {
    id: "edge-fundamental-controller",
    source: "node-fundamental",
    target: "node-controllers",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-create",
    source: "node-fundamental",
    target: "node-create-react-app",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-routing",
    source: "node-fundamental",
    target: "node-routing",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-database-relationships",
    source: "node-database",
    target: "node-relationships",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-forms",
    source: "node-fundamental",
    target: "node-forms",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-crud",
    source: "node-fundamental",
    target: "node-crud",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-database",
    source: "node-fundamental",
    target: "node-database",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-mvc",
    source: "node-fundamental",
    target: "node-mvc",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-relationships-relations",
    source: "node-relationships",
    target: "node-relations",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },





  // GREENS
  {
    id: "edge-fundamental-advanced",
    source: "node-fundamental",
    target: "node-advanced",
    animated: true,
    style: { stroke: "green" },
  },
  {
    id: "edge-advanced-mid",
    source: "node-advanced",
    target: "node-mid",
    animated: true,
    style: { stroke: "green" },
  },
  {
    id: "edge-head-fundamental",
    source: "node-head",
    target: "node-fundamental",
    animated: true,
    style: { stroke: "green" },
  },

  // END GREEN
  {
    id: "edge-database-migrations",
    source: "node-database",
    target: "node-migrations",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-database-seeders",
    source: "node-database",
    target: "node-seeders",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-routing-route-parameters",
    source: "node-routing",
    target: "node-route-parameters",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-routing-route-groups",
    source: "node-routing",
    target: "node-route-groups",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-blade",
    source: "node-fundamental",
    target: "node-blade",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-fundamental-auth",
    source: "node-fundamental",
    target: "node-auth",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-api",
    source: "node-advanced",
    target: "node-api",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-middleware",
    source: "node-advanced",
    target: "node-middleware",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-route-bindings",
    source: "node-advanced",
    target: "node-route-bindings",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-database-adv",
    source: "node-advanced",
    target: "node-database-adv",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-file",
    source: "node-advanced",
    target: "node-file",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-debug",
    source: "node-advanced",
    target: "node-debug",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-database-adv-query",
    source: "node-database-adv",
    target: "node-query",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-database-adv-accessors",
    source: "node-database-adv",
    target: "node-accessors",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-database-adv-collections",
    source: "node-database-adv",
    target: "node-collections",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-mail",
    source: "node-advanced",
    target: "node-mail",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-api-error",
    source: "node-api",
    target: "node-error",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-api-apps",
    source: "node-api",
    target: "node-apps",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-api-api-routes",
    source: "node-api",
    target: "node-api-routes",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-api-resources",
    source: "node-api",
    target: "node-resources",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-advanced-try",
    source: "node-advanced",
    target: "node-try",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-mid-eloquent-features",
    source: "node-mid",
    target: "node-eloquent-features",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-mid-raw",
    source: "node-mid",
    target: "node-raw",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-mid-jobs",
    source: "node-mid",
    target: "node-jobs",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-mid-observers",
    source: "node-mid",
    target: "node-observers",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-mid-caching",
    source: "node-mid",
    target: "node-caching",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-mid-only-api",
    source: "node-mid",
    target: "node-only-api",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
  {
    id: "edge-mid-file-api",
    source: "node-mid",
    target: "node-file-api",
    animated: true,
    style: { stroke: "rgb(195, 74, 54)" },
  },
];

export default InitialEdgesLaravel;