import React from "react";
import { Node, Position } from "reactflow";
import LaravelSvg from "../src/components/svg/laravelSvg";

const InitialElementsLaravel: Node<any>[] = [
  {
    id: "l-node-head",
    type: "NodeHead",
    sourcePosition: Position.Bottom,
    selectable: false,
    style: {
      padding: "0",
      minWidth: "260px",
      background: "none",
      border: "none",
    },
    data: {
      label: "Laravel",
      xp: "1",
      lvl: "2",
      Img: LaravelSvg,
    },
    position: { x: 1180, y: (1250 + 100) },
  },
  {
    id: "l-node-fundamental",
    style: {
      padding: "0",
      minWidth: "260px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    sourcePosition: Position.Bottom,
    targetPosition: Position.Top,
    data: {
      label: "Fundamental",
      biggerVariable: true,
      bottomSource: true,
    },
    position: { x: 1200, y: (1250 + 400) },
  },
  {
    id: "l-node-controllers",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Controllers",
    },
    position: { x: 800, y: (1250 + 400) },
  },
  {
    id: "l-node-blade",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Blade",
    },
    position: { x: 750, y: (1250 + 460) },
  },
  {
    id: "l-node-routing",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    sourcePosition: Position.Left,
    targetPosition: Position.Right,
    data: {
      label: "Routing",
    },
    position: { x: 780, y: (1250 + 520) },
  },
  {
    id: "l-node-auth",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Auth Basics",
    },
    position: { x: 840, y: (1250 + 570) },
  },
  {
    id: "l-node-route-parameters",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Parameters",
    },
    position: { x: 400, y: (1250 + 540) },
  },
  {
    id: "l-node-route-groups",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Groups",
    },
    position: { x: 350, y: (1250 + 600) },
  },
  {
    id: "l-node-crud",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "CRUD",
    },
    position: { x: 1600, y: (1250 + 400) },
  },
  {
    id: "l-node-forms",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "Forms, Validation and Form Requests",
    },
    position: { x: 1500, y: (1250 + 340) },
  },
  {
    id: "l-node-relationships",
    style: {
      padding: "0",
      minWidth: "420px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    data: {
      label: "Relationships",
    },
    position: { x: 1650, y: (1250 + 460) },
  },
  {
    id: "l-node-database",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    data: {
      label: "Database",
    },
    position: { x: 1430, y: (1250 + 515) },
  },
  {
    id: "l-node-mvc",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "MVC",
    },
    position: { x: 1560, y: (1250 + 570) },
  },
  {
    id: "l-node-migrations",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "Migrations",
    },
    position: { x: 1975, y: (1250 + 540) },
  },

  {
    id: "l-node-relations",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: ["hasOne", "hasMany", "belongsTo", "belongsToMany"],
    },
    position: { x: 1975, y: (1250 + 290) },
  },
  {
    id: "l-node-seeders",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "Seeders",
    },
    position: { x: 1950, y: (1250 + 600) },
  },
  {
    id: "l-node-advanced",
    style: {
      padding: "0",
      minWidth: "260px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    sourcePosition: Position.Bottom,
    targetPosition: Position.Top,
    data: {
      biggerVariable: true,
      bottomSource: true,
      label: "Advanced",
    },
    position: { x: 1200, y: (1250 + 700) },
  },
  {
    id: "l-node-middleware",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Middleware",
    },
    position: { x: 800, y: (1250 + 700) },
  },
  {
    id: "l-node-route-bindings",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Route Model Binding",
    },
    position: { x: 750, y: (1250 + 760) },
  },
  {
    id: "l-node-database-adv",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    sourcePosition: Position.Left,
    targetPosition: Position.Right,
    data: {
      label: "Database Advanced",
    },
    position: { x: 780, y: (1250 + 820) },
  },
  {
    id: "l-node-file",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "File Uploads",
    },
    position: { x: 890, y: (1250 + 880) },
  },
  {
    id: "l-node-debug",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Debug",
    },
    position: { x: 990, y: (1250 + 950) },
  },
  {
    id: "l-node-mail",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Mailables and Mail Facade, etc",
    },
    position: { x: 910, y: (1250 + 1020) },
  },
  {
    id: "l-node-query",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Eloquent Query Scopes",
    },
    position: { x: 400, y: (1250 + 840) },
  },
  {
    id: "l-node-collections",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    sourcePosition: undefined,
    data: {
      label: "Eloquent Collections",
    },
    position: { x: 350, y: (1250 + 900) },
  },
  {
    id: "l-node-accessors",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Top,
    data: {
      label: "Eloquent Accessors and Mutators",
    },
    position: { x: 560, y: (1250 + 960) },
  },
  {
    id: "l-node-api",
    style: { padding: "0", background: "none", border: "none" },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    data: {
      label: "API",
    },
    position: { x: 1360, y: (1250 + 775) },
  },
  {
    id: "l-node-error",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "API Error Handling and Status Codes",
    },
    position: { x: 1650, y: (1250 + 700) },
  },
  {
    id: "l-node-apps",
    style: {
      padding: "0",
      minWidth: "420px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "Postman, Insomnia, ThudnerClient",
    },
    position: { x: 1700, y: (1250 + 760) },
  },
  {
    id: "l-node-api-routes",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "API Routes and Controllers",
    },
    position: { x: 1680, y: (1250 + 820) },
  },
  {
    id: "l-node-resources",
    style: {
      padding: "0",
      minWidth: "420px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    sourcePosition: undefined,
    data: {
      label: "API Eloquent Resources",
    },
    position: { x: 1610, y: (1250 + 880) },
  },
  {
    id: "l-node-try",
    style: {
      padding: "0",
      minWidth: "420px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    sourcePosition: undefined,
    data: {
      label: "Try-Catch and Laravel Exceptions",
    },
    position: { x: 1460, y: (1250 + 940) },
  },
  {
    id: "l-node-mid",
    style: {
      padding: "0",
      minWidth: "260px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    sourcePosition: Position.Bottom,
    targetPosition: Position.Top,
    data: {
      biggerVariable: true,
      bottomSource: true,
      label: "Mid Level",
    },
    position: { x: 1200, y: (1250 + 1100) },
  },

  {
    id: "l-node-eloquent-features",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    data: {
      label: "All Eloquent Features",
    },
    position: { x: 720, y: (1250 + 1150) },
  },
  {
    id: "l-node-raw",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Top,
    data: {
      label: "Raw Database Queries",
    },
    position: { x: 960, y: (1250 + 1300) },
  },
  {
    id: "l-node-jobs",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Right,
    data: {
      label: "Jobs and Queues",
    },
    position: { x: 750, y: (1250 + 1225) },
  },
  {
    id: "l-node-observers",
    style: {
      padding: "0",
      minWidth: "250px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Top,
    data: {
      label: "Model Observers",
    },
    position: { x: 1200, y: (1250 + 1380) },
  },
  {
    id: "l-node-solid",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    data: {
      noTarget: true,
      label: "SOLID Code",
    },
    position: { x: 860, y: (1250 + 1480) },
  },
  {
    id: "l-node-large-database",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    data: {
      noTarget: true,
      label: "Large Database Structures",
    },
    position: { x: 500, y: (1250 + 1480) },
  },
  {
    id: "l-node-caching",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Top,
    data: {
      label: "Caching",
    },
    position: { x: 1440, y: (1250 + 1300) },
  },
  {
    id: "l-node-file-api",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    data: {
      label: "Upload Files via API",
    },
    position: { x: 1690, y: (1250 + 1225) },
  },
  {
    id: "l-node-only-api",
    style: {
      padding: "0",
      minWidth: "280px",
      background: "none",
      border: "none",
    },
    type: "NodeText",
    selectable: false,
    targetPosition: Position.Left,
    sourcePosition: undefined,
    data: {
      label: "Only-API Projects",
    },
    position: { x: 1720, y: (1250 + 1150) },
  },
];

export default InitialElementsLaravel;
